spring.application.name=noda-api

# 1. PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/noda_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=SAPin

# 2. Hibernate Relational Dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

# 3. SQL Logging Tools (Shows database actions in your terminal)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true